def build_markdown_report(records):
    """Membuat laporan markdown dari data."""
    header = "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |\n"
    header += "|---|---|---:|---:|:---:|\n"
    rows = [
        f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f}% | {r['nilai_akhir']:.2f} | {r['predikat']} |"
        for r in records
    ]
    return "# Rekap Nilai Mahasiswa\n\n" + header + "\n".join(rows) + "\n\nGenerated by student_performance_tracker"


def save_text(path, content):
    """Menyimpan teks ke file."""
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
